name: Deploy to FTP Hosting

on:
  push:
    branches: [ "production" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build-static

      - name: List output directory
        run: |
          ls -la
          ls -la out/ || echo "out directory not found"

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: out/
          server-dir: ${{ secrets.FTP_REMOTE_PATH }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**